[versions]
agp = "8.0.1"
kotlin = "1.8.10"
kotlin-coroutines = "1.6.4"
compose-kotlinCompiler = "1.4.3"
compose = "1.4.3"
lifecycle = "2.6.1"
retrofit = "2.9.0"
moshi = "1.15.0"
hilt = "2.43.2"
coil = "2.2.0"
room = "2.5.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

kotlin-library = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }

# Kotlin
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

#  Kotlin Coroutines
kotlin-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin.coroutines" }
kotlin-coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin.coroutines" }
kotlin-coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin.coroutines" }

#  Compose
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version = "1.2.0-alpha02" }

# AndroidX
androidx-core = { module = "androidx.core:core-ktx", version = "1.8.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.0" }
androidx-material = { module = "com.google.android.material:material", version = "1.9.0" }
androidx-navigation = { module = "androidx.navigation:navigation-compose", version = "2.6.0" }

# AndroidX Activity
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.5.1" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.5.1" }

# AndroidX Lifecycle
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }

#  Retrofit
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshiConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version = "4.10.0" }

#  Moshi
moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-annotationProcessor = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

#  Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }

#  Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room"}
room-kapt = { module = "androidx.room:room-compiler", version.ref = "room"}
room-coroutines = { module = "androidx.room:room-ktx", version.ref = "room"}

# Testing
junit = { module = "junit:junit", version = "4.13.2" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version = "1.1.5" }